# Generated by Django 5.1.1 on 2024-09-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Topic',
            new_name='topic',
        ),
    ]
